services:


  postgres:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
    ports:
      - '5434:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data

    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
