services:
  postgres:
    image: 'postgres:14.5'
    environment:
      - 'POSTGRES_DB=users'
      - 'POSTGRES_PASSWORD=1500002006501'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5434:5432'
    volumes:
      - './pg_data:/var/lib/postgresql/data'