spring:
  config:
    import: optional:file:.env[.properties]
  profile: dev
  datasource:
    url: jdbc:postgresql://${HOST}:5434/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  redis:
    host: ${HOST}
    port: 6379

server:
  port: 7071

logging:
  level:
    org:
      springframework:
        security: DEBUG

secret:
  key: ${SECRET_KEY}
