-- changeset: Stanislaw: demo-data-users
INSERT INTO users(username, email, password) VALUES
        ('stanislawcs', 'shukans588@gmail.com',
         '$2a$12$gAUlWvItcnv4rdGLS/Opwu16z1UuGImOprAkf99uRdUM7y4W.W/Ta'),
        ('marko', 'marko@gmail.com',
         '$2a$10$ZCj/74OrxeWzFcnRgI5xFOnbw87hsdYNrAQucrKHiQ7s.xDXGor0q'),
        ('eugene', 'eugene@mail.ru',
         '$2a$10$ZCj/74OrxeWzFcnRgI5xFOnbw87hsdYNrAQucrKHiQ7s.xDXGor0q'),
        ('artemios', 'artemios@gmail.com',
         '$2a$10$ZCj/74OrxeWzFcnRgI5xFOnbw87hsdYNrAQucrKHiQ7s.xDXGor0q'),
        ('sancho', 'sancho@gmail.com',
         '$2a$10$ZCj/74OrxeWzFcnRgI5xFOnbw87hsdYNrAQucrKHiQ7s.xDXGor0q'),
        ('matthew', 'matthew@yandex.ru',
         '$2a$10$ZCj/74OrxeWzFcnRgI5xFOnbw87hsdYNrAQucrKHiQ7s.xDXGor0q'),
        ('lehich', 'lehich@yandex.ru',
         '$2a$10$ZCj/74OrxeWzFcnRgI5xFOnbw87hsdYNrAQucrKHiQ7s.xDXGor0q'),
        ('arturio','arturio@yahoo.com',
         '$2a$10$ZCj/74OrxeWzFcnRgI5xFOnbw87hsdYNrAQucrKHiQ7s.xDXGor0q'),
        ('roman','roman@yandex.ru',
         '$2a$10$ZCj/74OrxeWzFcnRgI5xFOnbw87hsdYNrAQucrKHiQ7s.xDXGor0q'),
        ('diman','diman@gmail.com',
         '$2a$10$ZCj/74OrxeWzFcnRgI5xFOnbw87hsdYNrAQucrKHiQ7s.xDXGor0q'),
        ('makson','makson@yandex.ru',
         '$2a$10$ZCj/74OrxeWzFcnRgI5xFOnbw87hsdYNrAQucrKHiQ7s.xDXGor0q');